# -*- coding: utf-8 -*-
"""
===========================================
Program : LFL_Lab_Maintenance/Emailer.py
===========================================
Summary: Sends out an email when pulse tubes are off
         or when the fridge's temperature is >= 50mK
"""
__author__ = "Clark Miyamoto"

from BlueFors import BlueFors

folder_path =  r'C:\Users\lfl\Bluefors logs'

bf = BlueFors('bf_fridge',
              folder_path=folder_path,
              channel_vacuum_can=1,
              channel_pumping_line=2,
              channel_compressor_outlet=3,
              channel_compressor_inlet=4,
              channel_mixture_tank=5,
              channel_venting_line=6,
              channel_50k_plate=1,
              channel_4k_plate=2,
              channel_magnet=None,
              channel_still=6,
              channel_mixing_chamber=5)



from Emailer import Emailer
from .env import email_list, text_list


if (bf.get_pulse_tube_status()) == 0:
    subject = "[URGENT] BlueFors' pulse tubes are OFF"
    content = "This message has been automatically generated by BlueFors_Alarm script from LFL Emailer Bot."
    Email = Emailer(email_list, text_list,
            subjectLine=subject, 
            emailContent=content)
    Email.send_email()
    Email.sendtext()

if bf.get_temperature(6) >= 0.05:
    subject = f"[URGENT] BlueFors is WARM. Current temperature is {bf.get_temperature(6)} K"
    content = "This message has been automatically generated by BlueFors_Alarm script from LFL Emailer Bot."
    Email = Emailer(email_list, text_list,
            subjectLine=subject, 
            emailContent=content)
    Email.send_email()
    Email.sendtext()